name: Automerge

on:
  pull_request:
    types:
      - closed

# env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  # MY_REPO: https://github_username:${{secrets.GITHUB_TOKEN}}@github.com:mjones12209/POCSubBranch.git

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Rebase Master To Children
      run: bash /home/runner/work/POCSubBranch/POCSubBranch/scripts/update_children_branches.sh